### ISSUE TITLE
When will the code be released？

### ISSUE THREAD

**Issue by zhangweifeng919** [MengzhangLI/STFGNN#1]
When will the code be released？

**Comment by MengzhangLI** [comment]
> When will the code be released？

Hi, just a couple of days.

Best,

**Comment by hazdzz** [comment]
Open the code, please!

**Comment by MengzhangLI** [comment]
> Open the code, please! I'm so excited about the paper!

Hi, thanks for your recognition. Actually I'm writing the read.me. 

I will commit the code as soon as possible.

Best,

**Comment by MengzhangLI** [comment]
Hi, @hazdzz @zhangweifeng919 

I just upload the raw code of STFGNN. Hope this repository may be helpful to you. 

Contact me anytime if you meet  some troubles.

Best,

Mengzhang LI

**Comment by hazdzz** [comment]
> Hi, @hazdzz @zhangweifeng919
> 
> I just upload the raw code of STFGNN. Hope this repository may be helpful to you.
> 
> Contact me anytime if you meet some troubles.
> 
> Best,
> 
> Mengzhang LI

Thanks for releasing the code. If I find any bugs or issues, I would tell you as soon as possible.

**Comment by zhangweifeng919** [comment]
> Hi, @hazdzz @zhangweifeng919
> 
> I just upload the raw code of STFGNN. Hope this repository may be helpful to you.
> 
> Contact me anytime if you meet some troubles.
> 
> Best,
> 
> Mengzhang LI

thank you!

**Comment by zhangweifeng919** [comment]
thanks for releasing the code @MengzhangLI
