### ISSUE TITLE
算法1中没有看到α 

### ISSUE THREAD

**Issue by shuqincao** [MengzhangLI/STFGNN#10]
你好，文中描述The set of α which determines how many smallest numbers are treated in Alg. 1 is tricky and we would analysis it in the section of experiments.但是再算法1的伪代码中没有找到α ，还想请问下大佬算法1中的第6行到第7行的代码表示什么意思

**Comment by MengzhangLI** [comment]
> 你好，文中描述The set of α which determines how many smallest numbers are treated in Alg. 1 is tricky and we would analysis it in the section of experiments.但是再算法1的伪代码中没有找到α ，还想请问下大佬算法1中的第6行到第7行的代码表示什么意思

您好：

“算法1中的第6行到第7行的代码”：其实就是计算完N个时间序列彼此之间的距离（基于DTW, fast DTW or whatever other time series distance），然后排序。距离越小，时间序列之间的正相似性越强。然后截断选取靠前的比较小的时间序列距离。

α就相当于top个最小的距离。例如一个graph, node 数目为100. 构建的temporal graph 的稀疏性为5%。
那么α 就简单写成 100*0.05 = 5. 即我找对这个给定序列和它关系最近的5个序列，邻接矩阵的元素设置为1. 其余的94个node与这个点的邻接矩阵中的元素为0。实验结果表明它对于graph的表示能力是非常重要的。但我并没有fine tune这个参数，只是简单根据稀疏性取了一个值。

此致，

**Comment by MengzhangLI** [comment]
这种方法生成的temporal graph在一定程度上可以替代spatial graph. （当然得调整graph的稀疏性）

你可以在自己的数据集或模型上试一试，看看结果怎么样。

很期待你的反馈~
