### ISSUE TITLE
metr-la.csv文件怎么获取

### ISSUE THREAD

**Issue by wangzeyu135798** [MengzhangLI/STFGNN#11]
您好：
       请问metr-la.csv文件如何获取？

**Comment by MengzhangLI** [comment]
> 您好：
> 请问metr-la.csv文件如何获取？

您好，几周前才发现这个模型在metr-la和pems-bay的数值结果有问题。（因为Loss metric和PEMS0X的不一致）。

我已经跟aaai组委会发了邮件讲明情况，但一直没来得及更新github和arxiv。实在抱歉。

这个论文的模型的表现主要是在PEMS0x的4个数据集上SOTA了。

**Comment by wangzeyu135798** [comment]
PEMS03.csv如何获取？以及与adj_PEMS03.csv、adj_PEMS03_001.csv和adj_PEMS03_005.csv之间的关系是什么？

**Comment by MengzhangLI** [comment]
> PEMS03.csv如何获取？以及与adj_PEMS03.csv、adj_PEMS03_001.csv和adj_PEMS03_005.csv之间的关系是什么？

您好：

(1) PEMS03.csv应该在链接中可以获得：
https://pan.baidu.com/s/1ZPIiOM__r1TRlmY4YGlolw with password: p72z

(2) adj_PEMS03_001.csv和adj_PEMS03_005.csv 是生成的temporal graph的稀疏性。001的csv里面的graph稀疏性约等于0.01（不严格），而005里的约0.05. 

稀疏性是一个很重要的超参数，它最好和spatial graph的稀疏性保持一致。

**Comment by wangzeyu135798** [comment]
你好：
&nbsp; &nbsp; &nbsp; 那请问PEMS03.csv的含义是什么以及这个文件怎么生成呢？谢谢。






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MengzhangLI/STFGNN"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月26日(星期二) 晚上9:08
收件人:&nbsp;"MengzhangLI/STFGNN"<STFGNN@noreply.github.com&gt;;
抄送:&nbsp;"天津工业大学王泽宇"<1051533398@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [MengzhangLI/STFGNN] metr-la.csv文件怎么获取 (#11)





  
PEMS03.csv如何获取？以及与adj_PEMS03.csv、adj_PEMS03_001.csv和adj_PEMS03_005.csv之间的关系是什么？
  
您好：
 
(1) PEMS03.csv应该在链接中可以获得：
 https://pan.baidu.com/s/1ZPIiOM__r1TRlmY4YGlolw with password: p72z
 
(2) adj_PEMS03_001.csv和adj_PEMS03_005.csv 是生成的temporal graph的稀疏性。001的csv里面的graph稀疏性约等于0.01（不严格），而005里的约0.05.
 
稀疏性是一个很重要的超参数，它最好和spatial graph的稀疏性保持一致。

**Comment by MengzhangLI** [comment]
> 你好： &nbsp; &nbsp; &nbsp; 那请问PEMS03.csv的含义是什么以及这个文件怎么生成呢？谢谢。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "MengzhangLI/STFGNN" <notifications@github.com&gt;; 发送时间:&nbsp;2021年1月26日(星期二) 晚上9:08 收件人:&nbsp;"MengzhangLI/STFGNN"<STFGNN@noreply.github.com&gt;; 抄送:&nbsp;"天津工业大学王泽宇"<1051533398@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [MengzhangLI/STFGNN] metr-la.csv文件怎么获取 (#11) PEMS03.csv如何获取？以及与adj_PEMS03.csv、adj_PEMS03_001.csv和adj_PEMS03_005.csv之间的关系是什么？ 您好： (1) PEMS03.csv应该在链接中可以获得： https://pan.baidu.com/s/1ZPIiOM__r1TRlmY4YGlolw with password: p72z (2) adj_PEMS03_001.csv和adj_PEMS03_005.csv 是生成的temporal graph的稀疏性。001的csv里面的graph稀疏性约等于0.01（不严格），而005里的约0.05. 稀疏性是一个很重要的超参数，它最好和spatial graph的稀疏性保持一致。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

您好～

PEMS03.csv就是空间邻接矩阵的信息：

"from,to,cost"

每行分别表示 从node i 到node j 的距离/连通性。

**Comment by wangzeyu135798** [comment]
您好：
&nbsp; &nbsp; &nbsp; 我在使用PEMS03数据集做训练的时候，遇到了下面这个情况，请问这是什么原因？我的cuda版本是10.1，mx-net是1.7，我的安装方式为pip install mxnet-cu101







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MengzhangLI/STFGNN"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月26日(星期二) 晚上10:39
收件人:&nbsp;"MengzhangLI/STFGNN"<STFGNN@noreply.github.com&gt;;
抄送:&nbsp;"天津工业大学王泽宇"<1051533398@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [MengzhangLI/STFGNN] metr-la.csv文件怎么获取 (#11)





  
你好： &nbsp; &nbsp; &nbsp; 那请问PEMS03.csv的含义是什么以及这个文件怎么生成呢？谢谢。
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "MengzhangLI/STFGNN" <notifications@github.com&gt;; 发送时间:&nbsp;2021年1月26日(星期二) 晚上9:08 收件人:&nbsp;"MengzhangLI/STFGNN"<STFGNN@noreply.github.com&gt;; 抄送:&nbsp;"天津工业大学王泽宇"<1051533398@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [MengzhangLI/STFGNN] metr-la.csv文件怎么获取 (#11) PEMS03.csv如何获取？以及与adj_PEMS03.csv、adj_PEMS03_001.csv和adj_PEMS03_005.csv之间的关系是什么？ 您好： (1) PEMS03.csv应该在链接中可以获得： https://pan.baidu.com/s/1ZPIiOM__r1TRlmY4YGlolw with password: p72z (2) adj_PEMS03_001.csv和adj_PEMS03_005.csv 是生成的temporal graph的稀疏性。001的csv里面的graph稀疏性约等于0.01（不严格），而005里的约0.05. 稀疏性是一个很重要的超参数，它最好和spatial graph的稀疏性保持一致。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
您好～
 
PEMS03.csv就是空间邻接矩阵的信息：
 
"from,to,cost"
 
每行分别表示 从node i 到node j 的距离/连通性。

**Comment by MengzhangLI** [comment]
> 您好： &nbsp; &nbsp; &nbsp; 我在使用PEMS03数据集做训练的时候，遇到了下面这个情况，请问这是什么原因？我的cuda版本是10.1，mx-net是1.7，我的安装方式为pip install mxnet-cu101
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "MengzhangLI/STFGNN" <notifications@github.com&gt;; 发送时间:&nbsp;2021年1月26日(星期二) 晚上10:39 收件人:&nbsp;"MengzhangLI/STFGNN"<STFGNN@noreply.github.com&gt;; 抄送:&nbsp;"天津工业大学王泽宇"<1051533398@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [MengzhangLI/STFGNN] metr-la.csv文件怎么获取 (#11) 你好： &nbsp; &nbsp; &nbsp; 那请问PEMS03.csv的含义是什么以及这个文件怎么生成呢？谢谢。 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "MengzhangLI/STFGNN" <notifications@github.com&gt;; 发送时间:&nbsp;2021年1月26日(星期二) 晚上9:08 收件人:&nbsp;"MengzhangLI/STFGNN"<STFGNN@noreply.github.com&gt;; 抄送:&nbsp;"天津工业大学王泽宇"<1051533398@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [MengzhangLI/STFGNN] metr-la.csv文件怎么获取 (#11) PEMS03.csv如何获取？以及与adj_PEMS03.csv、adj_PEMS03_001.csv和adj_PEMS03_005.csv之间的关系是什么？ 您好： (1) PEMS03.csv应该在链接中可以获得： https://pan.baidu.com/s/1ZPIiOM__r1TRlmY4YGlolw with password: p72z (2) adj_PEMS03_001.csv和adj_PEMS03_005.csv 是生成的temporal graph的稀疏性。001的csv里面的graph稀疏性约等于0.01（不严格），而005里的约0.05. 稀疏性是一个很重要的超参数，它最好和spatial graph的稀疏性保持一致。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 您好～ PEMS03.csv就是空间邻接矩阵的信息： "from,to,cost" 每行分别表示 从node i 到node j 的距离/连通性。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

您卸载当前MXNet，然后重装个MXNet 1.5.1试一试？

**Comment by wangzeyu135798** [comment]
您好：
&nbsp; &nbsp; &nbsp;我按照您的建议换成了mxnet-cu101的1.5.1的版本，但是遇到了下面的情况一直没有调好，请问您之前遇到过吗？







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MengzhangLI/STFGNN"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月26日(星期二) 晚上10:48
收件人:&nbsp;"MengzhangLI/STFGNN"<STFGNN@noreply.github.com&gt;;
抄送:&nbsp;"天津工业大学王泽宇"<1051533398@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [MengzhangLI/STFGNN] metr-la.csv文件怎么获取 (#11)





  
您好： &nbsp; &nbsp; &nbsp; 我在使用PEMS03数据集做训练的时候，遇到了下面这个情况，请问这是什么原因？我的cuda版本是10.1，mx-net是1.7，我的安装方式为pip install mxnet-cu101
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "MengzhangLI/STFGNN" <notifications@github.com&gt;; 发送时间:&nbsp;2021年1月26日(星期二) 晚上10:39 收件人:&nbsp;"MengzhangLI/STFGNN"<STFGNN@noreply.github.com&gt;; 抄送:&nbsp;"天津工业大学王泽宇"<1051533398@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [MengzhangLI/STFGNN] metr-la.csv文件怎么获取 (#11) 你好： &nbsp; &nbsp; &nbsp; 那请问PEMS03.csv的含义是什么以及这个文件怎么生成呢？谢谢。 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "MengzhangLI/STFGNN" <notifications@github.com&gt;; 发送时间:&nbsp;2021年1月26日(星期二) 晚上9:08 收件人:&nbsp;"MengzhangLI/STFGNN"<STFGNN@noreply.github.com&gt;; 抄送:&nbsp;"天津工业大学王泽宇"<1051533398@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [MengzhangLI/STFGNN] metr-la.csv文件怎么获取 (#11) PEMS03.csv如何获取？以及与adj_PEMS03.csv、adj_PEMS03_001.csv和adj_PEMS03_005.csv之间的关系是什么？ 您好： (1) PEMS03.csv应该在链接中可以获得： https://pan.baidu.com/s/1ZPIiOM__r1TRlmY4YGlolw with password: p72z (2) adj_PEMS03_001.csv和adj_PEMS03_005.csv 是生成的temporal graph的稀疏性。001的csv里面的graph稀疏性约等于0.01（不严格），而005里的约0.05. 稀疏性是一个很重要的超参数，它最好和spatial graph的稀疏性保持一致。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 您好～ PEMS03.csv就是空间邻接矩阵的信息： "from,to,cost" 每行分别表示 从node i 到node j 的距离/连通性。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
您卸载当前MXNet，然后重装个MXNet 1.5.1试一试？
