### ISSUE TITLE
A_{TC}表示什么意思

### ISSUE THREAD

**Issue by shuqincao** [MengzhangLI/STFGNN#12]
大佬，您好，文章中A_{TC}的含义没有看懂， 为啥i=3N+l, and j=2N+l, A_{STFG(i,j)}=1呢

**Comment by MengzhangLI** [comment]
> 大佬，您好，文章中A_{TC}的含义没有看懂， 为啥i=3N+l, and j=2N+l, A_{STFG(i,j)}=1呢

参考自STSGCN的工作。意思是同一个道路口节点i，对应的位置为t时刻和t+1时刻的点，在这个4N*4N的Spatial-Temporal Fusion Graph里设置为1. 这样在之后的矩阵乘法操作里，可以利用到同一个道路口各个时刻先后的关系。

此致
