### ISSUE TITLE
想问问pytorch的版本

### ISSUE THREAD

**Issue by ZK-Zhou** [MengzhangLI/STFGNN#13]
您好，mxnet 版本着实看不懂，有无pytorch版本呢

**Comment by MengzhangLI** [comment]
> 您好，mxnet 版本着实看不懂，有无pytorch版本呢
我的这个用的STSGCN的版本改的，我很想PyTorch重构一遍但感觉自己没时间。

推荐你关注这个仓库: https://github.com/tsinghua-fib-lab/Traffic-Benchmark

这里面有很多模型，他们说“Moreover, the PyTorch version of baselines like GMAN and STSGCN is on the way~”

如果它们的代码放出，我可以很快的基于它们的代码改出来。

您没事也可看看这个仓库，我觉得整理的还不错。

**Comment by ZK-Zhou** [comment]
> > 您好，mxnet 版本着实看不懂，有无pytorch版本呢
> > 我的这个用的STSGCN的版本改的，我很想PyTorch重构一遍但感觉自己没时间。
> 
> 推荐你关注这个仓库: https://github.com/tsinghua-fib-lab/Traffic-Benchmark
> 
> 这里面有很多模型，他们说“Moreover, the PyTorch version of baselines like GMAN and STSGCN is on the way~”
> 
> 如果它们的代码放出，我可以很快的基于它们的代码改出来。
> 
> 您没事也可看看这个仓库，我觉得整理的还不错。

谢谢您，祝科研顺利
