### ISSUE TITLE
Download dataset

### ISSUE THREAD

**Issue by lsrock1** [MengzhangLI/STFGNN#16]
Thank you for your awesome work!
Download from baidu is almost impossible.
Could you share dataset on another platform or e-mail?

thanks.

**Comment by MengzhangLI** [comment]
Hi, sorry for my late reply.

Can you give me your e-mail? I will send PEMS0X dataset as soon as possible. 

Best,

**Comment by lsrock1** [comment]
Thank you for the reply.

My e-mail is ***@***.***

Thanks

2021년 5월 18일 (화) 오전 11:31, McMong ***@***.***>님이 작성:

**Comment by MengzhangLI** [comment]
Just send it to your gmail. Please check it.

Best,
