### ISSUE TITLE
引用详情

### ISSUE THREAD

**Issue by shuqincao** [MengzhangLI/STFGNN#17]
大佬，想引用你的文章，请问你文章具体bibtex是什么呢？谷歌学术上只能搜到arxiv， 搜不到被AAAI录用的详情

**Comment by MengzhangLI** [comment]
> 大佬，想引用你的文章，请问你文章具体bibtex是什么呢？谷歌学术上只能搜到arxiv， 搜不到被AAAI录用的详情

谢谢！这个文章不引也罢。

目前好像AAAI还没有出版版本，如果真的想引就引arxiv吧。

希望在交通、多维时间序列预测问题里，今年能做出真的有意义的值得被引用的工作。
