### ISSUE TITLE
PEMS07 dataset

### ISSUE THREAD

**Issue by ddrakulic** [MengzhangLI/STFGNN#18]
Hello,

i am interesting in the prediction in quite large networks but there is not a lot of models for this purpose. I think your work is great state-of-the-art method and I would like to test my model on PEMS07 dataset, but there is no way to download it from Baidu.

Can you please send it to me? My emal address is ddrakulic@gmail.com.

Thank you

**Comment by MengzhangLI** [comment]
Please check your e-mail.

Best,

**Comment by ddrakulic** [comment]
Thanks a lot for quick answer and for the datasets!

**Comment by jeongwhanchoi** [comment]
Hello @MengzhangLI ,
Could you please send the PEMS dataset to me?
There is no way to download it from Baidu.

My email address is jngwhn.choi@gmail.com .

Thank you :)

**Comment by MengzhangLI** [comment]
> Hello @MengzhangLI ,
> Could you please send the PEMS dataset to me?
> There is no way to download it from Baidu.
> 
> My email address is [jngwhn.choi@gmail.com](mailto:jngwhn.choi@gmail.com) .
> 
> Thank you :)

Hi, I just repost the e-mail. Could you download the dataset?

Best,

**Comment by jeongwhanchoi** [comment]
> > Hello @MengzhangLI ,
> > Could you please send the PEMS dataset to me?
> > There is no way to download it from Baidu.
> > My email address is [jngwhn.choi@gmail.com](mailto:jngwhn.choi@gmail.com) .
> > Thank you :)
> 
> Hi, I just repost the e-mail. Could you download the dataset?
> 
> Best,

Thanks for the quick response :)

**Comment by balyan7275** [comment]
@MengzhangLI could you please send pems07 dataset to Me. My email id is rahulkumar7275@gmail.com
Please help me out.

**Comment by FatemehZakeri-Z** [comment]
@MengzhangLI please send pems07 dataset to me too .
my email address is fatemehzakeri379@gmail.com
