### ISSUE TITLE
About the Graph Wavenet reported results

### ISSUE THREAD

**Issue by Factos001** [MengzhangLI/STFGNN#21]
Hi,

I found that the Graph Wavenet results reported in your paper seem to be incorrect. I understand that you just use the results from STSGCN, but it would be better to reproduce the results by yourself.

From what I have reproduced, Graph Wavenet achieves an average MAE (average of 12 steps) of 14.8 on PEMS-03, an average MAE of 19.4 on PEMS-04, and an average MAE of 14.9 on PEMS-08.

**Comment by MengzhangLI** [comment]
Hi, sorry for late reply.

Thanks very much for your nice suggestions and I would reproduce results by myself in the future research. Sorry for my direct copy of numerical results!

Wish you all the bset,
