### ISSUE TITLE
Evaluation Metrics

### ISSUE THREAD

**Issue by kevin-xuan** [MengzhangLI/STFGNN#24]
作者，你好。我看你们code里是让T=12，然后分别求出前1个horizon的MAE，前2个horizon的MAE，...，前12个horizon的MAE，用前12个horizon（也就是整个label和预测值pred）的MAE，MAPE和RMSE作为论文的最终结果，我的理解没错吧？

**Comment by MengzhangLI** [comment]
Yes, you are right.

The results is mean value of 12 time steps, not the 12-th. So only results on PEMS03, 04, 07, 08 are correct.

The metric is the same with STSGCN, different from those use PEMS-BAY and METR-LA. I found it after acceptance, after contacting with AAAI committe, we just keep 4 datasets results. 

Sorry again for my misleading results of first arxiv version.

Best,
