### ISSUE TITLE
temporal denpendencies

### ISSUE THREAD

**Issue by wanzhixiao** [MengzhangLI/STFGNN#3]
Hi,thanks for your excellent work!
I have a question, is the performance of Gated CNN berter than TCN?

**Comment by MengzhangLI** [comment]
> Hi,thanks for your excellent work!
> I have a question, is the performance of Gated CNN berter than TCN?

I think TCN can be added in this module only with some big modifications on STFGNN. The reasons I use Gated CNN are:
(1) 1D CNN with dilation rate=3 could be adaptively added into STFGN Layer.
(2) Gated Mechanism could really help model performance.

TCN is a great work, GraphWaveNet proves its perfirmance. However, it can hardly beat RNN/LSTM/transformer in many cases.
