### ISSUE TITLE
A question about APIs of MXNet used in stsgcn_4n_res.py

### ISSUE THREAD

**Issue by hazdzz** [MengzhangLI/STFGNN#5]
`return mx.sym.max(mx.sym.concat(*need_concat, dim=0), axis=0)`
I don't understand what is the meaning of `*need_concat`? What's the purpose of `*`?

**Comment by MengzhangLI** [comment]
> mx.sym.concat

Hi, it is usually used before a list variable in "mx.sym.concat( )" function in MXNet. I just followed what STSGCN did. 

For example, please see : https://github.com/apache/incubator-mxnet/issues/1578

"concat = mx.symbol.Concat(*[c1x1, c3x3, cd3x3, cproj] "

Best,

**Comment by hazdzz** [comment]
Well, the page of https://github.com/dmlc/mxnet/blob/master/example/kaggle-ndsb2/Train.R#L14-L19 is not found.

**Comment by hazdzz** [comment]
So, `*need_concat` which in `mx.sym.concat()` equals `need_concat` which out of `mx.sym.concat()`?

**Comment by MengzhangLI** [comment]
> So, `*need_concat` which in `mx.sym.concat()` equals `need_concat` which out of `mx.sym.concat()`?

To be honest, I don't know. I used to add "*" before a list variable in mx.sym.concat(). Maybe you can have a try without "*", I'm also interested in it, hoping for your feedback. ;)
