### ISSUE TITLE
Confusing code in stsgcn_4n_res.py

### ISSUE THREAD

**Issue by hazdzz** [MengzhangLI/STFGNN#6]
In `def  stsgcn(data, adj, label, input_length, num_of_vertices, num_of_features, filter_list, module_type, activation, use_mask=True, mask_init_value=None, temporal_emb=True, spatial_emb=True, prefix="", rho=1, predict_length=12)`, `mask_init_value` is `None`.
However, `if mask_init_value is None:`  is written in line 418 and `raise ValueError("mask init value is None!")` is written in line 419.
Isn't that contradictory?

**Comment by MengzhangLI** [comment]
> In `def stsgcn(data, adj, label, input_length, num_of_vertices, num_of_features, filter_list, module_type, activation, use_mask=True, mask_init_value=None, temporal_emb=True, spatial_emb=True, prefix="", rho=1, predict_length=12)`, `mask_init_value` is `None`.
> However, `if mask_init_value is None:` is written in line 418 and `raise ValueError("mask init value is None!")` is written in line 419.
> Isn't that contradictory?

Dear HAZDZZ:
It is not contradictory, I just followed default pipeline of STSGCN. In default setting, using mask matrix is a must thus error may raise if you set it None. 

Best,

**Comment by hazdzz** [comment]
I know you built STFGNN on STSGCN directly with a little modification. But, at least, you should understand his code, then change his code to build your model. As I compare your code and his code line by line, I must to say that you have no idea what you wrote in the code. It is such a pity that you write the code and the paper hastily without deep thinking.

**Comment by MengzhangLI** [comment]
> I know you built STFGNN on STSGCN directly with a little modification. But, at least, you should understand his code, then change his code to build your model. As I compare your code and his code line by line, I must to say that you have no idea what you wrote in the code. It is such a pity that you write the code and the paper hastily without deep thinking.

Sorry for your disappointment. However, to be honest, I don't agree with your opinion on me. The isssues you raise are usually about code function tech details which are not relevent about "deep thinking" and can be solved easily using Google. 

If I don't understand the code and do everything hastily, just finish a work, I can skip every issues or even don't release the code. However, this is not what I want. I would like to discuss with you. 

But I will take any statement you make. I do think STFGNN is not a fantastic work. I just make small but effective modifications on STSGCN. I also made many constructive discussions with Prof. Wan and Chao Song.

**Comment by MengzhangLI** [comment]
In this issue, mask matrix is helpful for model because it could improve some graph representations on traffic road.

If set None, the numerical results usually become worse and Chao made comparison on STSGCN paper. Thus he set mask matrix init value for better results. And I followed this set but delete .json file which does not set mask matrix in STFGNN because I know the results would become worse and nobody like it.

**Comment by MengzhangLI** [comment]
I really think STFGNN is not good. And its results on PEMS-BAY and METR-LA are not correct. Related talks are saved on closed issues. What a shame on me. 

I understand and appreciate your interest and passion in this research area. This framework may not helpful for you. But when implementing your models, you can generate a temporal graph, replace/fuse spatial adjacency matrix, it is usually helpful for model which I checked on many public and private dataset. 

Hoping discuss with you in the future if you want.

Best,
