### ISSUE TITLE
你好，请问pems-bay.csv合metr-la.csv文件怎么获取

### ISSUE THREAD

**Issue by shuqincao** [MengzhangLI/STFGNN#7]

**Comment by MengzhangLI** [comment]
Hi~ 

但实在抱歉，PEMS-BAY和METR-LA的结果有问题，因为loss和metric和pems0x不一样。再加上最近略忙，没来得及更新arxiv和github. 

这个论文的模型的表现主要是在PEMS0x的4个数据集上SOTA了。

**Comment by shuqincao** [comment]
你好，在PEMS08的数据集上，运行main_4n0_3layer_12T_res.py时，第477行的“ self._kwargs['value'] = val.tolist() if isinstance(val, np.ndarray) else val.asnumpy().tolist()” 也报错：AttributeError: 'list' object has no attribute 'asnumpy'，大佬能不能帮忙看看是什么问题呀？

**Comment by MengzhangLI** [comment]
> 你好，在PEMS08的数据集上，运行main_4n0_3layer_12T_res.py时，第477行的“ self._kwargs['value'] = val.tolist() if isinstance(val, np.ndarray) else val.asnumpy().tolist()” 也报错：AttributeError: 'list' object has no attribute 'asnumpy'，大佬能不能帮忙看看是什么问题呀？

您好，我晚上看一下吧。

我之前从没遇到过这个问题，感觉是package版本问题？

您可以先看看能否跑通STSGCN(https://github.com/Davidham3/STSGCN)，我是基于他的框架改的。如果他的能跑通，则是我的代码问题（但我之前没遇到这个error）。如果他的跑不通，那估计就是anaconda环境的问题了。

**Comment by shuqincao** [comment]
您好，我运行STSGCN也会出现这个问题，应该是我的环境的问题。

**Comment by MengzhangLI** [comment]
> 您好，我运行STSGCN也会出现这个问题，应该是我的环境的问题。

Hi~ 

查一下CUDNN/CUDA和对应的MXNet安装版本吧

我的环境是python 3.7, MXNet 1.5.1, CUDA Version: 11.1

**Comment by shuqincao** [comment]
好的，谢谢您！(*^▽^*)

**Comment by Andy-HuY** [comment]
请问pems-bay.csv和metr-la.csv文件怎么获取？
