### ISSUE TITLE
程序运行报错：AttributeError: 'list' object has no attribute 'asnumpy'。请问怎么解决呀？

### ISSUE THREAD

**Issue by shuqincao** [MengzhangLI/STFGNN#8]
![$5EU0%{(5A _LH}H`N})W1](https://user-images.githubusercontent.com/68112155/104983933-ae449a80-5a05-11eb-85d9-81c9ad4964da.png)

**Comment by wangzeyu135798** [comment]
+1 请问你现在解决了吗

**Comment by MengzhangLI** [comment]
> +1 请问你现在解决了吗

应该是MXNet版本不兼容导致的，请看这个issue：
https://github.com/MengzhangLI/STFGNN/issues/7

您可以查一下CUDNN/CUDA和对应的MXNet安装版本：
我的环境是python 3.7, MXNet 1.5.1, CUDA Version: 11.1
