### ISSUE TITLE
Question about dimensions of data

### ISSUE THREAD

**Issue by zyandtom** [MengzhangLI/STFGNN#9]
你好，为了方便叙述和解释，我这里用中文说一下：
![image](https://user-images.githubusercontent.com/71203151/105142009-f6aea600-5b34-11eb-84ec-c3a84af49b87.png)
这里提到，每一个STFGN Module的输入都是一个原输入的切片，每个切片的长度为K，然后经过Maxpool之后，K变为1，那么每个Module的输出维度不应该是1*N*d*C吗？为什么这里提到输出第一维是(T-K+1)？
![image](https://user-images.githubusercontent.com/71203151/105142528-adab2180-5b35-11eb-9f5f-4b5f39d26c22.png)

**Comment by MengzhangLI** [comment]
> 你好，为了方便叙述和解释，我这里用中文说一下：
> ![image](https://user-images.githubusercontent.com/71203151/105142009-f6aea600-5b34-11eb-84ec-c3a84af49b87.png)
> 这里提到，每一个STFGN Module的输入都是一个原输入的切片，每个切片的长度为K，然后经过Maxpool之后，K变为1，那么每个Module的输出维度不应该是1_N_d*C吗？为什么这里提到输出第一维是(T-K+1)？
> ![image](https://user-images.githubusercontent.com/71203151/105142528-adab2180-5b35-11eb-9f5f-4b5f39d26c22.png)

Hi, 感谢您的提问。

实在抱歉文章让您误会，我试着解释一下：

给定的序列长度为T，从中分别取出一片片长度为K的切片。

第一个STFGN Layer，序列长度T=12，切片K=4，那只能从12长度的序列(0-11)切 12-4+1=9个切片（0-3, 1-4, 2-5, 3-6, 4-7, 5-8, 6-9, 7-10, 8-11)。这9个切片各自过一个同size独立训练的STFGN Module，输出完再concat起来，得到T'=9 的序列作为第二个STFGN Layer的输入。

因此，每经过一个STFGN Layer，序列长度会变短，所以不能无限制的堆叠STFGN Layer。这与GraphWaveNet的TCN以及STSGCN一样。

此致，

**Comment by MengzhangLI** [comment]
文章里面有一些表述不清的地方，还没来得及修改，实在抱歉。

如果有别的问题，请随时问我。

谢谢

**Comment by zyandtom** [comment]
> 文章里面有一些表述不清的地方，还没来得及修改，实在抱歉。
> 
> 如果有别的问题，请随时问我。
> 
> 谢谢

原来如此，感谢解答！因为我还没有读GraphWaveNet和STSGCN，这就去学习一下

**Comment by kevin-xuan** [comment]
我认为输入数据X的维度是不是搞错了，一个X维度应该是(T, N, d)，经过一个全连接层是(T, N, C)才对吧，怎么变成4维了？
